-- =============================================================================
-- V19: modelo_plantilla → una fila por artículo (campos en CSV)
-- =============================================================================
-- Reestructura `modelo_plantilla`: de una fila por (artículo, campo) con FK a
-- `plantilla`, a UNA fila por artículo con los nombres de campo en una columna
-- `campos` TEXT (CSV). Se acepta perder la FK a `plantilla` (schema declarativo).
--
-- En dev/test (H2, ddl-auto=update sobre BD recreada) Hibernate crea la tabla ya
-- con `campos` y sin `id_plantilla`; el seed vive en data.sql. Este script es el
-- procedimiento MANUAL para PROD (MySQL), que conserva los datos existentes.
--
-- =============================================================================
-- BLOQUE MANUAL — SOLO PROD (MySQL) — ejecutar UNA vez, en orden
-- =============================================================================
--   -- 1) Nueva columna
--   ALTER TABLE modelo_plantilla ADD COLUMN campos TEXT;
--
--   -- 2) Backfill: agrupar los nombres de campo por artículo (tabla `plantilla`,
--   --    columna `nombre_campo`) en la fila de menor id de cada artículo.
--   UPDATE modelo_plantilla mp
--   JOIN (
--       SELECT MIN(mp2.id_modelo_plantilla) AS keep_id,
--              GROUP_CONCAT(p.nombre_campo ORDER BY p.id_plantilla SEPARATOR ',') AS campos
--       FROM modelo_plantilla mp2
--       JOIN plantilla p ON p.id_plantilla = mp2.id_plantilla
--       GROUP BY mp2.id_articulo
--   ) agg ON agg.keep_id = mp.id_modelo_plantilla
--   SET mp.campos = agg.campos;
--
--   -- 3) Borrar duplicados (dejar solo la fila de menor id por artículo).
--   DELETE mp FROM modelo_plantilla mp
--   JOIN (
--       SELECT id_articulo, MIN(id_modelo_plantilla) AS keep_id
--       FROM modelo_plantilla GROUP BY id_articulo
--   ) k ON k.id_articulo = mp.id_articulo
--   WHERE mp.id_modelo_plantilla <> k.keep_id;
--
--   -- 4) Soltar la FK (creada en V7) ANTES de eliminar la columna, y rematar.
--   ALTER TABLE modelo_plantilla DROP FOREIGN KEY fk_modelo_plantilla;
--   ALTER TABLE modelo_plantilla DROP COLUMN id_plantilla;
--   ALTER TABLE modelo_plantilla ADD CONSTRAINT uk_modelo_articulo UNIQUE (id_articulo);
--   ALTER TABLE modelo_plantilla MODIFY COLUMN campos TEXT NOT NULL;
-- =============================================================================
