-- V25__hoja_compra_item_oc_link.sql
--
-- Esta migración quedó como no-op: `oc_id` y `numero_oc` ya están mapeadas
-- en HojaCompraItemJpaEntity (@Column), por lo que Hibernate
-- (ddl-auto=update) las crea. El `ADD COLUMN IF NOT EXISTS` era redundante
-- y MySQL no lo soporta (ver V10__evn_item_costeo_columns.sql) → se retiró.
--
-- Se conserva el archivo (sin sentencias) para no alterar el versionado Flyway.
